[tool.poetry]
name = "stock-info-collector"
version = "0.1.0"
description = "Python library for collecting and archiving stock market information"
authors = ["Your Name <your.email@example.com>"]
packages = [
    { include = "stock_info_collector", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
yfinance = "^0.2.0"
requests = "^2.28.0"
pandas = "^1.5.0"
beautifulsoup4 = "^4.11.0"
boto3 = "^1.26.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-cov = "^4.0.0"
pytest-pythonpath = "^0.7.3"
black = "^22.3.0"
mypy = "^0.981"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
python_paths = ["src"]
